apiVersion: v1
data:
  hive-site.xml: |-
    <configuration>
        <property>
            <name>hive.imetastoreclient.factory.class</name>
            <value>com.amazonaws.glue.catalog.metastore.AWSGlueDataCatalogHiveClientFactory</value>
        </property>
        <property>
            <name>hive.metastore.warehouse.dir</name>
            <value>s3a://test.data.platform.arcadia/hive/warehouse</value>
        </property>
    </configuration>
kind: ConfigMap
metadata:
  namespace: spark
  name: spark-custom-config-map
