# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
jobs:
  setup:
    runs-on: ubuntu-latest
    outputs:
      mymatrix: ${{ steps.dataStep.outputs.mymatrix }}
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: 'Read tests folder'
        id: dataStep
        run: |
          echo "mymatrix=[$(find ./src/test/resources/com/arcadia/tahoe/features/* -maxdepth 1 -type d -exec basename {} \; | grep -v '^.$' | sed 's/.*/\\\"&\\\"/' | tr '\n' ',' | sed 's/,$//')]" >> $GITHUB_OUTPUT
  run-test:
    needs: setup
    runs-on: ubuntu-latest
    strategy:
      matrix:
        target: ${{ fromJson(needs.setup.outputs.mymatrix) }}
    steps:
      - run: echo ${{matrix.target}}
